# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodebaseInterface < Formula
  desc "A zero-dependency JSON-driven CLI"
  homepage "https://github.com/codebase-interface/cli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codebase-interface/cli/releases/download/v0.0.1/codebase-interface-darwin-amd64.tar.gz"
      sha256 "7e33569ebf8087e8e6ab9dc9eb68f81592f914632f2147340dd995a7473ca955"

      def install
        bin.install "codebase-interface"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codebase-interface/cli/releases/download/v0.0.1/codebase-interface-darwin-arm64.tar.gz"
      sha256 "073cf642993278ded26a0bf6139231a1fc3ea9faf40504c2dcbf14b5d048abc1"

      def install
        bin.install "codebase-interface"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codebase-interface/cli/releases/download/v0.0.1/codebase-interface-linux-amd64.tar.gz"
      sha256 "a6c4e0a01b48f9e87aff9bfd0418d75d929708a6a7c61e646406b0f72c2f2bba"
      def install
        bin.install "codebase-interface"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codebase-interface/cli/releases/download/v0.0.1/codebase-interface-linux-arm64.tar.gz"
      sha256 "440e830105c82684a39112dc4888462bbe096f6a39c51cd4921b41c4f7f52b73"
      def install
        bin.install "codebase-interface"
      end
    end
  end

  test do
    system "#{bin}/codebase-interface", "--version"
  end
end
